<a href="https://colab.research.google.com/github/mcd-unison/material-programacion/blob/main/intro-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="100">
</p>



# Curso Propedéutico en *Programación*

## Introducción a `python` resolviendo preguntas


**Julio Waissman Vilanova**



### Tipos

¿Cuales son los tipos de datos básicos? Revisa los tipos siguientes:

1. Tipos numéricos `int`, `float`, `complex`
2. Cadenas de caracteres
3. Tuplas
4. Listas
5. Diccionarios
6. Conjuntos

Da ejemplo de sobrecarga de operadores (en particular `+` y `*`)



In [ ]:
print("hola" + " como estas")
print("hola" * 5)
print(7 * 8)

hola como estas
holaholaholaholahola
56


¿Que significa que unos tipos sean *mutables* y otros *inmutables*?

Realiza un pequeño programa donde quede claro lo que significa que un tipo de datos sea mutable, e ilustra el uso del método `copy.deepcopy()`.

In [ ]:
# Los datos que son mutables son aquellos que pueden cambiar y modificarse despues de haberlos creado, como por ejemplo las listas, diccionarios, conjuntos.
# En cambio los datos inmutables son aquellos que no pueden ser modificados una vez creados, como por ejemplo los tipos de numeros, las cadenas de caracteres, tulpas.

# Añadimos la bilbioteca copy
import copy

# Creamos una lista con distintos tipos de datos
l = [2, "hola", [3, 4, 5], {"num" : 789}, 4.5, 10]

# Creamos la copia de la lista
l2 = copy.deepcopy(l)

# Agregamos un dato mas para probar que es mutable
l2.append("mutable")

# Imprimimos
print(l)
print(l2)

[2, 'hola', [3, 4, 5], {'num': 789}, 4.5, 10]
[2, 'hola', [3, 4, 5], {'num': 789}, 4.5, 10, 'mutable']


### *Comprehension* de listas, conjuntos y diccionarios

Escribe, en una sola linea, una expresión que genere una lista con la raíz cuadrada de todos los números enteros que se encuentran entre $1$ y $n$
que sean divisibles por $3$ y $7$ y que el dígito menos significativo del número sea $6$.

In [ ]:
n = 10_000

# Escribe aqui el *one linner*
lista = [ x**(1/2) for x in range(1, n + 1)
          if x % 3 == 0 and x % 7 == 0 and x % 10 == 6]

print(lista)

[11.224972160321824, 18.33030277982336, 23.366642891095847, 27.49545416973504, 31.080540535840107, 34.292856398964496, 37.22902093797257, 39.949968710876355, 42.49705872175156, 44.8998886412873, 47.18050444834179, 49.35585071701227, 51.43928459844674, 53.44155686354955, 55.37147279962851, 57.23635208501674, 59.04235767650204, 60.794736614282655, 62.49799996799898, 64.15605972938177, 65.7723346096214, 67.34983296193094, 68.89121859859934, 70.39886362719217, 71.87489130426563, 73.32121111929344, 74.73954776421918, 76.13146524269712, 77.49838707999025, 78.8416133777081, 80.16233529532433, 81.4616474176652, 82.74055837375042, 84.0, 85.24083528450434, 86.46386528486914, 87.66983517721475, 88.85943956609225, 90.033327162779, 91.19210492142398, 92.33634170791044, 93.46657156438339, 94.58329662260668, 95.68698971124549, 96.77809669548166, 97.85703858180054, 98.92421341612983, 99.9799979995999]


### Funciones

Escribe una función que:

1. reciba una lista de elementos (letras, números, lo que sea),
2. cuente la ocurrencia de cada elemento en la lista,
3. devuelva las ocurrencias en forma de diccionario,
4. si imprime es True, imprima un histograma de ocurrencias, por ejemplo:

```python

lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]

d = funcion_ejemplo(lista, imprime = True)

1    		***** 	(5 -> 50%)
'a'  		***   	(3 -> 30%)
13		*	(1 -> 10%)
'hola'		*	(1 -> 10%)

```

In [ ]:
lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]

# Escribe la función aquí
def funcion_ejemplo(lista, imprime=False):
  """
  Genera un diccionario con las ocurrencias de cada elemento diferente lista.

  Si imprime==True, imprime en pantalla las ocurrencias
  """
  d = { x: lista.count(x) for x in set(lista)}

  if imprime:
    for (key, val) in d.items():
      print(f"{key}\t\t{val * '*'}\t\t({val} --> {val / len(lista):.0%})")

  return d

d = funcion_ejemplo(lista, imprime = True)
print(d)

1		*****		(5 --> 50%)
a		***		(3 --> 30%)
13		*		(1 --> 10%)
hola		*		(1 --> 10%)
{1: 5, 'a': 3, 13: 1, 'hola': 1}


In [ ]:
# Realiza pruebas aquí
lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]
d = {}

for item in lista:
  x = lista.count(item)
  d[item] = x

print(d)

{1: 5, 'a': 3, 13: 1, 'hola': 1}


Escribe una función que modifique un diccionario y regrese el diccionario modificado y una copia del original, donde cada entrada
del diccionario sea una lista de valores. Ten en cuenta que si una entrada del diccionario es de tipo mutable, al modificarlo en la
copia se modifica el original. Utiliza el modulo `copy` para evitar este problema. Ejemplo de la función:

```python
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'febrero')

print(dic1)
{'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}

print(dic2)
{'Pepe':[12, 'febrero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
```

In [ ]:
# Escribe la función fundicos aquí
def fundicos(dic, persona, posicion, mes):
  """
  Genera una nueva version del diccionario dic1. Podemos cambiar los meses de cada persona mientras mantengamos la posicion como 1

  Nos regresa el diccionario modificado y una copia del original
  """
  # Primero hacemos la copia, y luego ya podemos obtener nuestro nuevo diccionario
  dic_copy = copy.deepcopy(dic)
  dic_v2 = dic

  # Cambiamos el mes
  dic_v2[persona][posicion] = mes

  return "Version modificada: {} y copia original: {}".format(dic_v2, dic_copy)

In [ ]:
# Realiza pruebas de fundicos aquí
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'febrero')

print(dic1) # Observamos que como los diccionarios son mutables, este se modifica
print(dic2)

{'Pepe': [12, 'febrero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}
Version modificada: {'Pepe': [12, 'febrero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]} y copia original: {'Pepe': [12, 'enero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}


### Generadores

Escribe un generador que reciba una lista y genere todas las permutaciones que se puedan hacer con los elementos de la lista

In [ ]:
# Escribe aqui fun1

def permutaciones(lista):
    """
    Permutaciones de los elementos de una lista.

    Devuelve un generador con todas las permutaciones posibles de los elementos de la lista de entrada
    """
    if len(lista) == 0:
      yield lista
    else:
      for (i, elemento) in enumerate(lista):
        lista_menos_elem = lista[:i] + lista[i+1:]
        for perm in permutaciones(lista_menos_elem):
          yield [elemento] + perm

In [ ]:
# Realiza pruebas de fun2 aquí
for p in permutaciones(['a', 'b', 'c', 'd']):
    print(p)

['a', 'b', 'c', 'd']
['a', 'b', 'd', 'c']
['a', 'c', 'b', 'd']
['a', 'c', 'd', 'b']
['a', 'd', 'b', 'c']
['a', 'd', 'c', 'b']
['b', 'a', 'c', 'd']
['b', 'a', 'd', 'c']
['b', 'c', 'a', 'd']
['b', 'c', 'd', 'a']
['b', 'd', 'a', 'c']
['b', 'd', 'c', 'a']
['c', 'a', 'b', 'd']
['c', 'a', 'd', 'b']
['c', 'b', 'a', 'd']
['c', 'b', 'd', 'a']
['c', 'd', 'a', 'b']
['c', 'd', 'b', 'a']
['d', 'a', 'b', 'c']
['d', 'a', 'c', 'b']
['d', 'b', 'a', 'c']
['d', 'b', 'c', 'a']
['d', 'c', 'a', 'b']
['d', 'c', 'b', 'a']


Ahora escribe una función que reciba 4 digitos del 0 al 9, y devuelva una lista con todas las horas váidas que se puedan hacer con estos dígitos en forma de lista de strings con la forma `"HH:MM"`.

In [ ]:
def horas_validas(lista):
    """
    Calcula las horas posibles al darle 4 numeros como lista, utilizando la funcion permutacion que hicimos previamente

    Devuelve una lista con las horas en formato de HH:MM
    """
    horas = []
    for i in permutaciones(lista):

      if i[2] <= 5 and i[1] <= 4 and i[0] <= 2:
        horas.append(str(i[0]) + str(i[1]) + ":" + str(i[2]) + str(i[3]))
    return horas

Validando:

In [ ]:
print(horas_validas([1,2,3,7]))

['12:37', '13:27', '21:37', '23:17']


Escribe una función, lo más compacta posible, que escoja entre los 3 patrones ascii a continuación, e imprima en pantalla
el deseado, pero de dimensión $n$ ($n \ge 4$), toma en cuanta que para algunos valores de $n$ habrá
algún(os) patrones que no se puedan hacer.

```
          *             ++++           oooooooo
          **            ++++           ooo  ooo
          ***           ++++           oo    oo
          ****          ++++           o      o
          *****             ++++       o      o
          ******            ++++       oo    oo
          *******           ++++       ooo  ooo
          ********          ++++       oooooooo

```

In [76]:
# Escribe aquí la función
def patron(figure, n):
  i = 1

# Triangulo, 1er figura
  if figure == "triangulo":
    while i <= n:
      print("*" * i)
      i += 1

# Rectangulo, 2da figura
  elif figure == "rectangulo":
    if n % 2 == 0:
      mitad = n / 2
      while i <= mitad:
        print("+" * 4)
        i += 1
      while i <= n:
        print(" " * 4, "+" * 4)
        i += 1
    else:
      print("Por favor, inserte una n que sea par.")

# Rombo, 3era figura
  elif figure == "rombo":
# Para generar la parte de arriba del rombo
    for i in range(1, n + 1):
      if i == 1:
        print("o" * (n - i) + "o" * (n - i))
      elif i == 2:
        print("o" * (n - i) + " " * i + "o" * (n - i))
      elif i == 3:
        print("o" * (n - i) + " " * (i + 1) + "o" * (n - i))
      elif i == 4:
        print("o" * (n - i) + " " * (i + 2) + "o" * (n - i))

# Para generar la parte de abajo del rombo
    for i in range(n - 1, 0, -1):
      if i == 1:
        print("o" * (n - i) + "o" * (n - i))
      elif i == 2:
        print("o" * (n - i) + " " * i + "o" * (n - i))
      elif i == 3:
        print("o" * (n - i) + " " * (i + 1) + "o" * (n - i))
      elif i == 4:
        print("o" * (n - i) + " " * (i + 2) + "o" * (n - i))

  return ""

In [77]:
#Realiza pruebas aquí
print(patron("triangulo", 8))
print(patron("rectangulo", 8))
print(patron("rombo", 5))

*
**
***
****
*****
******
*******
********

++++
++++
++++
++++
     ++++
     ++++
     ++++
     ++++

oooooooo
ooo  ooo
oo    oo
o      o
o      o
oo    oo
ooo  ooo
oooooooo



### Clases y objetos

Diseña una clase Matriz con las siguientes características:

1. Como inicialización de un objeto es necesario conocer $n$, $m$ y tipo. En caso de no proporcionar $m$ la matriz se asume cuadrada de $n \times n$. En caso de no proporcionar $n$ la matriz tendrá una dimensión de $1 \times 1$.
2. De no especificarse todos los elementos se inicializan a 0, a menos que exista un tipo especial ( `unos` o `diag` por el momento).
3. Implementa con sobrecarga la suma de matrices, la multiplicación de matrices y la multiplicación por un escalar.
4. Implementa como métodos eliminar columna y eliminar fila.   
5. Programa la representación visual de la matriz.
6. Ten en cuenta tambien el manejo de errores.


Ejemplo de uso:

```
>>> A = Matriz(n=3, m=4)

>>> print(A)
0 0 0 0
0 0 0 0
0 0 0 0

>>> A = A.quitafila(2)

>>> print(A)
0 0 0 0
0 0 0 0

>>> B = Matriz(4,4,'diag')

>>> print(B)
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1

>>> C = Matriz(4,1,'unos')

>>> print(C)
1
1
1
1

>>> D = 3 * B * C

>>> print(D)
3
3
3
3

>>> E = 3 * B + C
error "No seas menso, si no son de la misma dimensión las matrices no se pueden sumar"
```

In [139]:
import numpy as np

def matriz(n, m, tipo):
    '''
    Crea una matriz al introducir los valores de n y m

    Nos devuelve la matriz creada
    '''
    # Tomaremos a 0 como si no se tuviera el valor de m o n
    # Si m=0 --> m=n, si n=0 --> m=n=1

    if m == 0:
      m = n
    elif n == 0:
      n = 1
      m = 1

    matrix = []

####### En caso de querer una matriz diagonal
    if tipo == "diag":
      matrix = np.eye(m) # Aplicamos la herramienta np.eye para crear la matriz diagonal

####### En caso de querer una matriz con solo unos
    if tipo == "unos":
      for i in range(m):
          matrix.append([]) # Se crean las listas que vienen siendo los renglones
          for j in range(n):
            matrix[i].append(1) # Se introduce cada numero que va en los renglones

####### En caso de no especificar la matriz, se crea una con solo ceros
    if tipo == "":
      for i in range(m):
          matrix.append([]) # Se crean las listas que vienen siendo los renglones
          for j in range(n):
            matrix[i].append(0) # Se introduce cada numero que va en los renglones

####### En caso de querer escribir una matriz especifica
    if tipo == "norm":
      for i in range(m):
          matrix.append([])
          print("Ingresar numeros de renglon {}, uno a la vez.".format(i + 1))
          for j in range(n):
            matrix[i].append(int(input("Agrega numero: ")))

    return matrix

In [140]:
# Suma de matrices

def matriz_sum(A, B):
    """
    Se suman las matrices A y B

    Nos devuelve la suma de las dos matrices, llamada C
    """
    m = len(A)
    n = len(A[0])

    if len(A) == len(B) and len(A[0]) == len(B[0]): # Primero vemos si la suma es posible
      C = []

      for i in range(m):
        C.append([]) # Aqui se va creando cada renglon
        for j in range(n):
          C[i].append(A[i][j] + B[i][j]) # Se le va añadiendo cada suma a los renglones correspondientes
    else:
      print("No se puede realizar la suma, pues las dimensiones de las matrices no coinciden.")

    return C

In [132]:
matriz_sum(matriz(2, 2, "diag"), matriz(2, 2, "norm"))

Ingresar numeros de renglon 1, uno a la vez.
Agrega numero: 2
Agrega numero: 2
Ingresar numeros de renglon 2, uno a la vez.
Agrega numero: 2
Agrega numero: 2


[[3.0, 2.0], [2.0, 3.0]]

In [142]:
# Eliminar columnas y filas

def delcol(self, n=0): #donde n es la columna a quitar
    if n == 0:
      print("Ninguna columna ha sido elminiada")
    else:
      for x in range(len(self.values)):
         self.values[x].pop(n - 1)
      print(f"La columna {n} ha sido elminada\n")

In [ ]:
A = matriz(3, 3, "")
print('A =', A)

A.remove(A[1])
print('A = ', A)

A = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
A =  [[0, 0, 0], [0, 0, 0]]


PRUEBAS:

In [145]:
A = matriz(3, 4, "norm")
print('A =', A)

Ingresar numeros de renglon 1, uno a la vez.
Agrega numero: 2
Agrega numero: 1
Agrega numero: 3
Ingresar numeros de renglon 2, uno a la vez.
Agrega numero: 5
Agrega numero: 7
Agrega numero: 2
Ingresar numeros de renglon 3, uno a la vez.
Agrega numero: 4
Agrega numero: 1
Agrega numero: 9
Ingresar numeros de renglon 4, uno a la vez.
Agrega numero: 2
Agrega numero: 5
Agrega numero: 7
A = [[2, 1, 3], [5, 7, 2], [4, 1, 9], [2, 5, 7]]


In [ ]:
A = A.quitafila(2)
print('A = ', A)

In [144]:
# Realiza las pruebas a la clase aquí

B = matriz(4,4,'diag')
print('B = ', B)

C = matriz(4,1,'unos')
print('C =', C)

D = 3 * B * C
print('D = ', D)

E = 3 * B + C
print('E = ', E)

B =  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
C = [[1, 1, 1, 1]]
D =  [[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]
E =  [[4. 1. 1. 1.]
 [1. 4. 1. 1.]
 [1. 1. 4. 1.]
 [1. 1. 1. 4.]]
